<a href="https://colab.research.google.com/github/trailmarkerlib/pythonWorkshop/blob/main/grief_to_action_python_workshop_01_10_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Grief to Action Python Workshop: Jan 10, 2024

### Pittsburgh Police Arrest Data
Data</br>
https://data.wprdc.org/dataset/arrest-data/resource/e03a89dd-134a-4ee8-a2bd-62c40aeebc6f?inner_span=True<br/><br/>
Data Dictionary</br>
https://data.wprdc.org/dataset/arrest-data/resource/e554650d-f48f-49b2-88f3-e19878a1c245?inner_span=True


#### Import packages

In [4]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [5]:
import json
import requests

#### Read the data using WPRDC API

In [6]:
url = 'https://data.wprdc.org/api/3/action/datastore_search?resource_id=e03a89dd-134a-4ee8-a2bd-62c40aeebc6f'

In [7]:
data = json.loads(requests.get(url).text)

In [8]:
#data

In [9]:
pd.json_normalize(data)

help  success  \
0  https://data.wprdc.org/api/3/action/help_show?...     True   

   result.include_total  result.limit result.records_format  \
0                  True           100               objects   

                     result.resource_id result.total_estimation_threshold  \
0  e03a89dd-134a-4ee8-a2bd-62c40aeebc6f                              None   

                                      result.records  \
0  [{'_id': 1, 'PK': '1975272', 'CCR': '16158872'...   

                                       result.fields  \
0  [{'id': '_id', 'type': 'int'}, {'id': 'PK', 't...   

                                 result._links.start  \
0  /api/3/action/datastore_search?resource_id=e03...   

                                  result._links.next  result.total  \
0  /api/3/action/datastore_search?resource_id=e03...         65659   

   result.total_was_estimated  
0                       False

In [10]:
data['result']['records'][0:3]

[{'_id': 1,
  'PK': '1975272',
  'CCR': '16158872',
  'AGE': 42,
  'GENDER': 'F',
  'RACE': 'B',
  'ARRESTTIME': '2016-08-24T12:20:00',
  'ARRESTLOCATION': '4700 Block Centre AV Pittsburgh, PA 15213',
  'OFFENSES': '3929 Retail Theft.',
  'INCIDENTLOCATION': '4700 Block Centre AV Pittsburgh, PA 15213',
  'INCIDENTNEIGHBORHOOD': 'Bloomfield',
  'INCIDENTZONE': '5',
  'INCIDENTTRACT': '804',
  'COUNCIL_DISTRICT': '8',
  'PUBLIC_WORKS_DIVISION': '2',
  'X': -79.94927741,
  'Y': 40.45255125},
 {'_id': 2,
  'PK': '1974456',
  'CCR': '16144120',
  'AGE': 31,
  'GENDER': 'M',
  'RACE': 'W',
  'ARRESTTIME': '2016-08-03T14:55:00',
  'ARRESTLOCATION': '4200 Block Steubenville PKE Pittsburgh, PA 15205',
  'OFFENSES': '13(a)(16) Possession of Controlled Substance',
  'INCIDENTLOCATION': '4200 Block Steubenville PKE Pittsburgh, PA 15205',
  'INCIDENTNEIGHBORHOOD': 'Outside City',
  'INCIDENTZONE': 'OSC',
  'INCIDENTTRACT': '5599',
  'COUNCIL_DISTRICT': None,
  'PUBLIC_WORKS_DIVISION': None,
  'X': 

In [11]:
pd.json_normalize(data['result']['records'])

_id       PK       CCR   AGE GENDER RACE           ARRESTTIME  \
0     1  1975272  16158872  42.0      F    B  2016-08-24T12:20:00   
1     2  1974456  16144120  31.0      M    W  2016-08-03T14:55:00   
2     3  1974466  16144165  63.0      F    B  2016-08-03T16:45:00   
3     4  1974550  16145257  25.0      F    W  2016-08-05T02:36:00   
4     5  1974596  16145962  25.0      M    B  2016-08-06T02:00:00   
..  ...      ...       ...   ...    ...  ...                  ...   
95   96  1975358  16162854  35.0      M    B  2016-08-29T23:33:00   
96   97  1974535  16145596  25.0      F    B  2016-08-05T15:26:00   
97   98  1974941  16155030  34.0      M    W  2016-08-18T22:46:00   
98   99  1974954  16091081  20.0      M    B  2016-09-07T01:30:00   
99  100  1974940  16154303  27.0      M    W  2016-08-17T22:28:00   

                                      ARRESTLOCATION  \
0          4700 Block Centre AV Pittsburgh, PA 15213   
1   4200 Block Steubenville PKE Pittsburgh, PA 15205   
2         900 Block Freeport RD Fox Chapel, PA 15238   
3        Foreland ST & Cedar AV Pittsburgh, PA 15212   
4          900 Block Woodlow ST Pittsburgh, PA 15205   
..                                               ...   
95        700 Block Brushton AV Pittsburgh, PA 15221   
96        5800 Block Forward AV Pittsburgh, PA 15217   
97       lamar ST & Williams RD Pittsburgh, PA 15212   
98             900 Block 2ND AV Pittsburgh, PA 15219   
99            900 Block Mina ST Pittsburgh, PA 15212   

                                             OFFENSES  \
0                                  3929 Retail Theft.   
1        13(a)(16) Possession of Controlled Substance   
2                                  3929 Retail Theft.   
3   5503 Disorderly Conduct. / 5505 Public Drunken...   
4   2702 Aggravated Assault. / 2705 Recklessy Enda...   
..                                                ...   
95  13(a)(16) Possession of Controlled Substance /...   
96  13(a)(16) Possession of Controlled Substance /...   
97       13(a)(16) Possession of Controlled Substance   
98  2706 Terroristic Threats. / 2701(a)(3) Simple ...   
99  2706 Terroristic Threats. / 5104 Resisting Arr...   

                                    INCIDENTLOCATION   INCIDENTNEIGHBORHOOD  \
0          4700 Block Centre AV Pittsburgh, PA 15213             Bloomfield   
1   4200 Block Steubenville PKE Pittsburgh, PA 15205           Outside City   
2         900 Block Freeport RD Fox Chapel, PA 15238               Westwood   
3        Foreland ST & Cedar AV Pittsburgh, PA 15212         East Allegheny   
4          900 Block Woodlow ST Pittsburgh, PA 15205        Crafton Heights   
..                                               ...                    ...   
95        700 Block Brushton AV Pittsburgh, PA 15221         Homewood South   
96        5800 Block Forward AV Pittsburgh, PA 15217    Squirrel Hill South   
97       lamar ST & Williams RD Pittsburgh, PA 15212      Northview Heights   
98         2600 Block Centre AV Pittsburgh, PA 15219        Terrace Village   
99            900 Block Mina ST Pittsburgh, PA 15212  Spring Hill-City View   

   INCIDENTZONE INCIDENTTRACT COUNCIL_DISTRICT PUBLIC_WORKS_DIVISION  \
0             5           804                8                     2   
1           OSC          5599             None                  None   
2             5          2811                9                     2   
3             1          2304                1                     1   
4             5          2814                2                     5   
..          ...           ...              ...                   ...   
95            5          1304                9                     2   
96            4          1408                5                     3   
97            1          2609                1                     1   
98            2           510                6                     3   
99            1          2620                1                     1   

   

In [12]:
df_from_api = pd.json_normalize(data['result']['records'])

#### Explore the data

In [13]:
df_from_api.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   _id                    100 non-null    int64  
 1   PK                     100 non-null    object 
 2   CCR                    100 non-null    object 
 3   AGE                    98 non-null     float64
 4   GENDER                 100 non-null    object 
 5   RACE                   100 non-null    object 
 6   ARRESTTIME             100 non-null    object 
 7   ARRESTLOCATION         100 non-null    object 
 8   OFFENSES               100 non-null    object 
 9   INCIDENTLOCATION       100 non-null    object 
 10  INCIDENTNEIGHBORHOOD   97 non-null     object 
 11  INCIDENTZONE           100 non-null    object 
 12  INCIDENTTRACT          97 non-null     object 
 13  COUNCIL_DISTRICT       92 non-null     object 
 14  PUBLIC_WORKS_DIVISION  92 non-null     object 
 15  X      

#### Read the data from downloaded CSV file

In [14]:
csv_url = 'https://raw.githubusercontent.com/trailmarkerlib/pythonWorkshop/main/data/e03a89dd-134a-4ee8-a2bd-62c40aeebc6f.csv'

In [15]:
df_from_csv = pd.read_csv(csv_url)

<ipython-input-15-92457aacf929>:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df_from_csv = pd.read_csv(csv_url)


In [16]:
df_from_csv = pd.read_csv(csv_url, low_memory = False)

In [17]:
df_from_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65659 entries, 0 to 65658
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   _id                    65659 non-null  int64  
 1   PK                     65659 non-null  int64  
 2   CCR                    65659 non-null  int64  
 3   AGE                    65256 non-null  float64
 4   GENDER                 65659 non-null  object 
 5   RACE                   65659 non-null  object 
 6   ARRESTTIME             65659 non-null  object 
 7   ARRESTLOCATION         65659 non-null  object 
 8   OFFENSES               65656 non-null  object 
 9   INCIDENTLOCATION       65659 non-null  object 
 10  INCIDENTNEIGHBORHOOD   63199 non-null  object 
 11  INCIDENTZONE           65559 non-null  object 
 12  INCIDENTTRACT          63222 non-null  float64
 13  COUNCIL_DISTRICT       55592 non-null  float64
 14  PUBLIC_WORKS_DIVISION  55592 non-null  float64
 15  X 

#### Choose data to explore

In [20]:
df_init = df_from_csv.copy()

In [21]:
df_init.columns

Index(['_id', 'PK', 'CCR', 'AGE', 'GENDER', 'RACE', 'ARRESTTIME',
       'ARRESTLOCATION', 'OFFENSES', 'INCIDENTLOCATION',
       'INCIDENTNEIGHBORHOOD', 'INCIDENTZONE', 'INCIDENTTRACT',
       'COUNCIL_DISTRICT', 'PUBLIC_WORKS_DIVISION', 'X', 'Y'],
      dtype='object')

In [22]:
df_init.columns.to_list()

['_id',
 'PK',
 'CCR',
 'AGE',
 'GENDER',
 'RACE',
 'ARRESTTIME',
 'ARRESTLOCATION',
 'OFFENSES',
 'INCIDENTLOCATION',
 'INCIDENTNEIGHBORHOOD',
 'INCIDENTZONE',
 'INCIDENTTRACT',
 'COUNCIL_DISTRICT',
 'PUBLIC_WORKS_DIVISION',
 'X',
 'Y']

In [29]:
df_init['GENDER'].unique()

array(['F', 'M', 'U'], dtype=object)

In [30]:
df_init['RACE'].unique()

array(['B', 'W', 'H', 'O', 'U', 'A', 'I'], dtype=object)

In [31]:
df_init['AGE'].unique()

array([ 42.,  31.,  63.,  25.,  45.,  29.,  21.,  17.,  14.,  30.,  54.,
        27.,  53.,  18.,  22.,  23.,  33.,  41.,  26.,  15.,  35.,  32.,
        13.,  19.,  52.,  40.,  16.,  20.,  28.,  nan,  36.,  37.,  44.,
        24.,  57.,  48.,  34.,  47.,  49.,  58.,  59.,  46.,  51.,  56.,
        38.,  43.,  60.,  10.,  50.,  39.,  55.,  69.,  61.,  12.,  67.,
        65.,  71.,  62.,  70.,  66.,  79.,   0.,  75.,  88.,  11.,  77.,
        68.,  64.,  74.,  82.,  76.,  73.,  72., 999.,  80., 117.,  83.,
        84.,  98.,  78.,  81.,  90.])

In [32]:
df_init['INCIDENTNEIGHBORHOOD'].unique()

array(['Bloomfield', 'Outside City', 'Westwood', 'East Allegheny',
       'Crafton Heights', 'Greenfield', 'Brookline', 'Regent Square',
       'East Liberty', nan, 'East Hills', 'Carrick', 'Allegheny Center',
       'South Side Flats', 'Sheraden', 'East Carnegie',
       'Golden Triangle/Civic Arena', 'Point Breeze North', 'Perry South',
       'Allentown', 'North Shore', 'Marshall-Shadeland',
       'Central Oakland', 'Middle Hill', 'Strip District',
       'Lincoln-Lemington-Belmar', 'Central Northside',
       'Troy Hill-Herrs Island', 'Highland Park', 'Homewood North',
       'Northview Heights', 'Brighton Heights', 'Hazelwood',
       'Perry North', 'Bedford Dwellings', 'Elliott', 'Beechview',
       'Fineview', 'Glen Hazel', 'Spring Hill-City View', 'Bluff',
       'Manchester', 'Homewood West', 'Outside County', 'Point Breeze',
       'Homewood South', 'Squirrel Hill South', 'Terrace Village',
       'Upper Lawrenceville', 'Arlington', 'South Side Slopes',
       'Lower Lawrenc

In [33]:
df_init['INCIDENTZONE'].unique()

array(['5', 'OSC', '1', '4', '6', '3', '2', nan], dtype=object)

In [34]:
df_init['INCIDENTTRACT'].unique()

array([ 804., 5599., 2811., 2304., 2814., 1517., 1919., 1410., 1115.,
         nan, 1306., 2901., 2204., 1702., 3206., 2022., 1609., 2805.,
        201., 1405., 2614., 1803., 2205., 2704.,  405.,  501.,  203.,
       1201., 2206., 2406., 1102., 1301., 2609., 2708.,  903., 1515.,
       2602., 1302.,  509., 2020., 1920., 2509., 1504., 2620., 2715.,
        103., 2902., 2107., 1207., 6699., 1917., 1406., 1916., 1304.,
       1408.,  510., 1011., 1603., 1608., 1303.,  603., 1017., 1918.,
       2018., 3102., 2904., 1208., 1807., 2507.,  802., 2023., 1806.,
       1921., 1202., 1106., 1706., 1809., 3001.,  806., 1516., 2108.,
        305.,  605., 2808., 2019.,  709., 1014., 1114., 3204.,  807.,
       2703.,  507., 2815.,  902., 2812.,  506.,  409.,  402., 2615.,
       2412., 1204., 1413., 2201.,  809., 1914., 1016., 2701., 1606.,
        703., 1903., 1005., 2017.,  705.,  901., 1113., 1401., 2503.,
       1501.,  406., 1607., 1915., 1404., 2612., 1203., 2607.,  708.,
        706., 1604.,

#### Convert variables to int, float, datetime

In [35]:
df_init['ARRESTTIME'] = pd.to_datetime(df_init['ARRESTTIME'])

In [36]:
df_init['AGE'] = df_init['AGE'].astype('Int64')

In [37]:
df_init['X'] = df_init['X'].astype('float')

In [38]:
df_init['Y'] = df_init['Y'].astype('float')

#### Create list of offenses and get number for each person

In [39]:
df_init['list_of_offenses'] = [str(x).split('/') for x in df_init['OFFENSES']]

In [40]:
df_init['number_of_offenses'] = [len(x) for x in df_init['list_of_offenses']]

In [41]:
df_init['number_of_offenses'].unique()

array([ 1,  2,  4,  3,  7,  6,  5,  8,  9, 13, 10, 12, 14, 11, 15, 17, 16,
       18, 19, 22])

In [46]:
df_init.loc[df_init['number_of_offenses'] == 22]['list_of_offenses'].to_list()

[['903 Criminal Conspiracy. ',
  ' 907 Possessing Instruments of Crime. ',
  ' 3925 Receiving Stolen Property. ',
  ' 5104 Resisting Arrest or Other Law Enforcement. ',
  ' 6105(a)(1) Persons not to possess, use, manufacture, control, sell or transfer firearms: Former Convict enumerated in subsection (b) ',
  ' 6106 Firearms not to be Carried without a License. ',
  ' 1501 Drivers Required to be Licensed. ',
  ' 1543 Driving While Operating Privilege is Suspended or Revoked. ',
  ' 3301 Driving on Right Side of Roadway. ',
  ' 3303 Overtaking Vehicle on the Left. ',
  ' 3309 Driving on Roadways Laned for Traffic. ',
  ' 3310 Following Too Closely. ',
  ' 3334 Turning Movements and Required Signals. ',
  ' 3351 Stop, Stand and Park Outside Bus. and Res.  ',
  ' 3354 Additional Parking Regulations. ',
  ' 3361  Driving Vehicle at Safe Speed. ',
  ' 13(a)(16) Possession of Controlled Substance ',
  ' 13(a)(30) Possession w',
  ' Intent to Del. Controlled Substance ',
  ' 3712 Abandonment 